// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_collect_2000_coins = "CgkI15G5ibEREAIQCg"; // <GPGSID>
        public const string leaderboard_most_active_player = "CgkI15G5ibEREAIQCA"; // <GPGSID>
        public const string achievement_collect_500_coins = "CgkI15G5ibEREAIQAw"; // <GPGSID>
        public const string achievement_kill_100_enemies = "CgkI15G5ibEREAIQDA"; // <GPGSID>
        public const string achievement_kill_1000_enemies = "CgkI15G5ibEREAIQDg"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI15G5ibEREAIQBA"; // <GPGSID>
        public const string achievement_kill_2000_enemies = "CgkI15G5ibEREAIQDw"; // <GPGSID>
        public const string leaderboard_most_money_earned = "CgkI15G5ibEREAIQBw"; // <GPGSID>
        public const string achievement_collect_1000_coins = "CgkI15G5ibEREAIQCQ"; // <GPGSID>
        public const string achievement_kill_500_enemies = "CgkI15G5ibEREAIQDQ"; // <GPGSID>
        public const string achievement_collect_3000_coins = "CgkI15G5ibEREAIQCw"; // <GPGSID>

}

